name: Find and Replace Stage Deployment

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Find and Replace - elementor - Stage
      run: |
        grep -c dev-geo.ca test-file.txt 
        find . -not -path ../github/workflow -prune -o -exec sed -i 's/dev.geo.ca/stage.geo.ca/g' {} \;
        find . -not -path ../github/workflow -prune -o -exec sed -i 's/geocore-dev.api.geo.ca/geocore-stage.api.geo.ca/g' {} \;
        grep -c dev-geo.ca test-file.txt     

    - name: Push changes - Stage
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Commit - Stage
        push_options: --force
        branch: stage
    
    - name: Push changes - Init Prod
      run: git push origin -f stage:prod