name: Find and Replace Stage Deployment

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Find and Replace - elementor - Stage
      run: |
        pwd
        grep -c dev.geo.ca test-file.txt || true
        find -not -path './.git*' -type f -exec sed -i 's/dev.geo.ca/stage.geo.ca/g' {} \;
        find -not -path './.git*' -type f -exec sed -i 's/geocore-dev.api.geo.ca/geocore-stage.api.geo.ca/g' {} \;
        grep -c dev.geo.ca test-file.txt || true    
        cat test-file.txt
